using System.Collections.Generic;

namespace MaschinenDataein.Helper
{
    public static class AlarmnamenHelper
    {
        public static readonly Dictionary<int, string> Alarmnamen = new Dictionary<int, string>
        {  

{ 1, "Schutzabdeckung, Siegelwerkzeug Einlauf!" },
{ 2, "Lichtschrankeneingriff!" },
{ 3, "Schutzabdeckung, Formwerkzeug Auslauf!" },
{ 4, "Schutzabdeckung, Formwerkzeug Einlauf!" },
{ 5, "Druckluftmangel!" },
{ 6, "Störung, Kühlwasserkreislauf!" },
{ 7, "Störung, Folientransport (Frequenzumrichter)!" },
{ 8, "Störung, Folientransport (Positionierung)!" },
{ 9, "Not-Aus betätigt!" },
{ 10, "Stopschalter betätigt!" },
{ 11, "Schutzabdeckungen nicht geschlossen!" },
{ 12, "Schutzabdeckung, Packungsaustragtunnel!" },
{ 13, "Schutzabdeckung, Längsschneidung!" },
{ 14, "Schutzabdeckung, Querschneidung!" },
{ 15, "Schutzabdeckung, Siegelwerkzeug Auslauf!" },
{ 16, "Störung, Lichtschranken-Überwachungsgerät!" },
{ 17, "Siegelwerkzeug schließt nicht!" },
{ 18, "Oberfolienformstation ist nicht geöffnet!" },
{ 19, "Oberfolienformstation schließt nicht!" },
{ 20, "Signal Druckmarke fehlt!" },
{ 21, "Störung, Fremdgerät!" },
{ 22, "Formstempel nicht oben!" },
{ 23, "Endvakuum wird nicht erreicht!" },
{ 24, "Störung, Gasdruck (Gasflaschen leer)!" },
{ 25, "Störung, Folientransport (Fehlimpulse/Drahtbruch Drehgeber)!" },
{ 26, "Störung, Packungsaustragsband!" },
{ 27, "Motorschutzschalter ausgelöst!" },
{ 28, "Störung, Konturschneider!" },
{ 29, "Störung, externe Vakuumpumpe!" },
{ 30, "Formwerkzeug ist nicht geöffnet!" },
{ 31, "Siegelwerkzeug ist nicht geöffnet!" },
{ 32, "Formwerkzeug schließt nicht!" },
{ 33, "CPU Puffer-Batterie leer! (Bitte austauschen)" },
{ 34, "Temperaturalarm, Vorheizen 1 (unten)!" },
{ 35, "Temperaturalarm, Vorheizen 1 (oben)!" },
{ 36, "Temperaturalarm, Formstempel!" },
{ 37, "Temperaturalarm, Siegeln!" },
{ 38, "Drahtbruch (Pt100) Vorheizen unten!" },
{ 39, "Drahtbruch (Pt100) Vorheizen oben!" },
{ 40, "Drahtbruch (Pt100) Formstempel!" },
{ 41, "Endbegasungsdruck wird nicht erreicht!" },
{ 42, "Folienende Unterfolie!" },
{ 43, "Folienende Oberfolie!" },
{ 44, "Störung, Etikettierer/Printer 1!" },
{ 45, "Störung, Etikettierer/Printer 2!" },
{ 46, "Kabel/Stecker vom Formwerkzeugdeckel nicht in Steckdose eingesteckt!" },
{ 47, "Temperaturalarm Oberfolienformstation!" },
{ 48, "Phasenfolge falsch! (Linksdrehfeld)" },
{ 49, "Drahtbruch (Pt100) Siegeln!" },
{ 50, "Magnetschalter, Formwerkzeugdeckel!" },
{ 51, "Schutzabdeckung, vor Oberfolieneinlauf und Siegelwerkzeug!" },
{ 52, "Schutzabdeckung, Etikettierbereich!" },
{ 53, "Sicherheitskreis Schutzabdeckung!" },
{ 54, "Muldenkontrolle nicht oben!" },
{ 55, "Produktkontrolle nicht oben!" },
{ 56, "Störung, Profibus!" },
{ 57, "Werkzeuge im Vorschub geschlossen! (Wert 2, Folientransport Optionen)" },
{ 58, "Störung, Füller 1!" },
{ 59, "Heizungstemperatur zu hoch!" },
{ 60, "Heißpräger, Farbbandende!" },
{ 61, "Störung, Produktkontrolle!" },
{ 62, "Störung, Höhenkontrolle!" },
{ 63, "Störung, Einlegehilfe!" },
{ 64, "Störung, Füller 2!" },
{ 65, "Querschneidung 1 nicht unten!" },
{ 66, "Querschneidung 2 nicht unten!" },
{ 67, "Störung, Verfahrung Querschneidung!" },
{ 68, "Störung, Etikettierer/Printer 3!" },
{ 69, "Temperaturalarm, Vorheizen 2 (unten)!" },
{ 70, "Temperaturalarm, Vorheizen 2 (oben)!" },
{ 71, "Temperaturalarm, Vorheizen 3 (unten)!" },
{ 72, "Temperaturalarm, Vorheizen 3 (oben)!" },
{ 73, "BDE Eingabe falsch!" },
{ 74, "Haltevakuum Trägerplatte!" },
{ 75, "Störung Unterfolienabrollung!" },
{ 76, "Programmdaten ungültig!" },
{ 77, "Störung, Formwerkzeug, Formatwechsler!" },
{ 78, "Format im Formwerkzeug fehlt!" },
{ 79, "Störung Ziehtiefe!" },
{ 80, "Störung Stempeltiefe!" },
{ 81, "Klebestellenüberwachung aktiviert!" },
{ 82, "Störung, Sensoren im Formwerkzeug!" },
{ 83, "Störung, Sensoren im Siegelwerkzeug!" },
{ 84, "Display-Puffer-Batterie austauschen! Hauptschalter nicht ausschalten!" },
{ 85, "Randstreifen noch in der Kette!" },
{ 86, "Folie nicht in der Kette!" },
{ 87, "Störung Frequenzumrichter Werkzeuglift!" },
{ 88, "Tür Werkzeuglift offen!" },
{ 89, "Störung Profibusverbindung Servo Querschneidung!" },
{ 90, "Störung Servo Verfahrung Querschneidung!" },
{ 91, "Querschneidung 3!" },
{ 92, "Störung, Klebetisch Unterfolie!" },
{ 93, "Störung, Etikettierer/Printer 4!" },
{ 94, "Störung, Etikettierer/Printer 5!" }

        };
    }
}
