// <auto-generated />
using System;
using MaschinenDataein.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MaschinenDataein.Migrations
{
    [DbContext(typeof(MaschinenDbContext))]
    [Migration("20250926095253_Version1.1")]
    partial class Version11
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MaschinenDataein.Models.Data.AbzugsDaten", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("Abzuglaenge")
                        .HasColumnType("bigint");

                    b.Property<long>("MaschinenId")
                        .HasColumnType("bigint");

                    b.Property<int>("PRnummer")
                        .HasColumnType("int");

                    b.Property<long>("PackungenproAbzug")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MaschinenId");

                    b.ToTable("Abzugsdaten");
                });

            modelBuilder.Entity("MaschinenDataein.Models.Data.AlarmDaten", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<bool>("AM1")
                        .HasColumnType("bit");

                    b.Property<bool>("AM10")
                        .HasColumnType("bit");

                    b.Property<bool>("AM11")
                        .HasColumnType("bit");

                    b.Property<bool>("AM12")
                        .HasColumnType("bit");

                    b.Property<bool>("AM13")
                        .HasColumnType("bit");

                    b.Property<bool>("AM14")
                        .HasColumnType("bit");

                    b.Property<bool>("AM15")
                        .HasColumnType("bit");

                    b.Property<bool>("AM16")
                        .HasColumnType("bit");

                    b.Property<bool>("AM17")
                        .HasColumnType("bit");

                    b.Property<bool>("AM18")
                        .HasColumnType("bit");

                    b.Property<bool>("AM19")
                        .HasColumnType("bit");

                    b.Property<bool>("AM2")
                        .HasColumnType("bit");

                    b.Property<bool>("AM20")
                        .HasColumnType("bit");

                    b.Property<bool>("AM21")
                        .HasColumnType("bit");

                    b.Property<bool>("AM22")
                        .HasColumnType("bit");

                    b.Property<bool>("AM23")
                        .HasColumnType("bit");

                    b.Property<bool>("AM24")
                        .HasColumnType("bit");

                    b.Property<bool>("AM25")
                        .HasColumnType("bit");

                    b.Property<bool>("AM26")
                        .HasColumnType("bit");

                    b.Property<bool>("AM27")
                        .HasColumnType("bit");

                    b.Property<bool>("AM28")
                        .HasColumnType("bit");

                    b.Property<bool>("AM29")
                        .HasColumnType("bit");

                    b.Property<bool>("AM3")
                        .HasColumnType("bit");

                    b.Property<bool>("AM30")
                        .HasColumnType("bit");

                    b.Property<bool>("AM31")
                        .HasColumnType("bit");

                    b.Property<bool>("AM32")
                        .HasColumnType("bit");

                    b.Property<bool>("AM33")
                        .HasColumnType("bit");

                    b.Property<bool>("AM34")
                        .HasColumnType("bit");

                    b.Property<bool>("AM35")
                        .HasColumnType("bit");

                    b.Property<bool>("AM36")
                        .HasColumnType("bit");

                    b.Property<bool>("AM37")
                        .HasColumnType("bit");

                    b.Property<bool>("AM38")
                        .HasColumnType("bit");

                    b.Property<bool>("AM39")
                        .HasColumnType("bit");

                    b.Property<bool>("AM4")
                        .HasColumnType("bit");

                    b.Property<bool>("AM40")
                        .HasColumnType("bit");

                    b.Property<bool>("AM41")
                        .HasColumnType("bit");

                    b.Property<bool>("AM42")
                        .HasColumnType("bit");

                    b.Property<bool>("AM43")
                        .HasColumnType("bit");

                    b.Property<bool>("AM44")
                        .HasColumnType("bit");

                    b.Property<bool>("AM45")
                        .HasColumnType("bit");

                    b.Property<bool>("AM46")
                        .HasColumnType("bit");

                    b.Property<bool>("AM47")
                        .HasColumnType("bit");

                    b.Property<bool>("AM48")
                        .HasColumnType("bit");

                    b.Property<bool>("AM49")
                        .HasColumnType("bit");

                    b.Property<bool>("AM5")
                        .HasColumnType("bit");

                    b.Property<bool>("AM50")
                        .HasColumnType("bit");

                    b.Property<bool>("AM51")
                        .HasColumnType("bit");

                    b.Property<bool>("AM52")
                        .HasColumnType("bit");

                    b.Property<bool>("AM53")
                        .HasColumnType("bit");

                    b.Property<bool>("AM54")
                        .HasColumnType("bit");

                    b.Property<bool>("AM55")
                        .HasColumnType("bit");

                    b.Property<bool>("AM56")
                        .HasColumnType("bit");

                    b.Property<bool>("AM57")
                        .HasColumnType("bit");

                    b.Property<bool>("AM58")
                        .HasColumnType("bit");

                    b.Property<bool>("AM59")
                        .HasColumnType("bit");

                    b.Property<bool>("AM6")
                        .HasColumnType("bit");

                    b.Property<bool>("AM60")
                        .HasColumnType("bit");

                    b.Property<bool>("AM61")
                        .HasColumnType("bit");

                    b.Property<bool>("AM62")
                        .HasColumnType("bit");

                    b.Property<bool>("AM63")
                        .HasColumnType("bit");

                    b.Property<bool>("AM64")
                        .HasColumnType("bit");

                    b.Property<bool>("AM65")
                        .HasColumnType("bit");

                    b.Property<bool>("AM66")
                        .HasColumnType("bit");

                    b.Property<bool>("AM67")
                        .HasColumnType("bit");

                    b.Property<bool>("AM68")
                        .HasColumnType("bit");

                    b.Property<bool>("AM69")
                        .HasColumnType("bit");

                    b.Property<bool>("AM7")
                        .HasColumnType("bit");

                    b.Property<bool>("AM70")
                        .HasColumnType("bit");

                    b.Property<bool>("AM71")
                        .HasColumnType("bit");

                    b.Property<bool>("AM72")
                        .HasColumnType("bit");

                    b.Property<bool>("AM73")
                        .HasColumnType("bit");

                    b.Property<bool>("AM74")
                        .HasColumnType("bit");

                    b.Property<bool>("AM75")
                        .HasColumnType("bit");

                    b.Property<bool>("AM76")
                        .HasColumnType("bit");

                    b.Property<bool>("AM77")
                        .HasColumnType("bit");

                    b.Property<bool>("AM78")
                        .HasColumnType("bit");

                    b.Property<bool>("AM79")
                        .HasColumnType("bit");

                    b.Property<bool>("AM8")
                        .HasColumnType("bit");

                    b.Property<bool>("AM80")
                        .HasColumnType("bit");

                    b.Property<bool>("AM81")
                        .HasColumnType("bit");

                    b.Property<bool>("AM82")
                        .HasColumnType("bit");

                    b.Property<bool>("AM83")
                        .HasColumnType("bit");

                    b.Property<bool>("AM84")
                        .HasColumnType("bit");

                    b.Property<bool>("AM85")
                        .HasColumnType("bit");

                    b.Property<bool>("AM86")
                        .HasColumnType("bit");

                    b.Property<bool>("AM87")
                        .HasColumnType("bit");

                    b.Property<bool>("AM88")
                        .HasColumnType("bit");

                    b.Property<bool>("AM89")
                        .HasColumnType("bit");

                    b.Property<bool>("AM9")
                        .HasColumnType("bit");

                    b.Property<bool>("AM90")
                        .HasColumnType("bit");

                    b.Property<bool>("AM91")
                        .HasColumnType("bit");

                    b.Property<bool>("AM92")
                        .HasColumnType("bit");

                    b.Property<bool>("AM93")
                        .HasColumnType("bit");

                    b.Property<bool>("AM94")
                        .HasColumnType("bit");

                    b.Property<long>("MaschinenId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MaschinenId");

                    b.ToTable("Alarmdaten");
                });

            modelBuilder.Entity("MaschinenDataein.Models.Data.LeistungsDaten", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("MaschinenId")
                        .HasColumnType("bigint");

                    b.Property<int>("Maschinentakte")
                        .HasColumnType("int");

                    b.Property<int>("PRnummer")
                        .HasColumnType("int");

                    b.Property<int>("Packungszaeler")
                        .HasColumnType("int");

                    b.Property<int>("Tagestaktzaehler")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MaschinenId");

                    b.ToTable("Leistungsdaten");
                });

            modelBuilder.Entity("MaschinenDataein.Models.Data.Maschine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAdresse")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Maschinen");
                });

            modelBuilder.Entity("MaschinenDataein.Models.Data.Maschinenprogrammen", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("MaschinenId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PRnummer")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaschinenId");

                    b.ToTable("MaschinenProgrammen");
                });

            modelBuilder.Entity("MaschinenDataein.Models.Data.Planungs", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Artikel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeSpan?>("Bis")
                        .HasColumnType("time");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Fertigware")
                        .HasColumnType("int");

                    b.Property<string>("Grund")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Kartonsanzahl")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("MHD")
                        .HasColumnType("date");

                    b.Property<long>("MaschineID")
                        .HasColumnType("bigint");

                    b.Property<int?>("Pause")
                        .HasColumnType("int");

                    b.Property<int?>("PersonalIst")
                        .HasColumnType("int");

                    b.Property<string>("Personalnamen")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("Personalsoll")
                        .HasColumnType("int");

                    b.Property<int?>("Sollmenge")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("Starten")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("Stoppen")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("Von")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("Planungs");
                });

            modelBuilder.Entity("MaschinenDataein.Models.Data.StoerungsDaten", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("MaschinenId")
                        .HasColumnType("bigint");

                    b.Property<long>("StoerungsmeldungId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MaschinenId");

                    b.HasIndex("StoerungsmeldungId");

                    b.ToTable("Stoerungsdaten");
                });

            modelBuilder.Entity("MaschinenDataein.Models.Data.StoerungsMeldung", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Meldung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Stoerungsmeldung");
                });

            modelBuilder.Entity("MaschinenDataein.Models.Data.TemperaturDaten", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Isstemp1")
                        .HasColumnType("int");

                    b.Property<int>("Isstemp2")
                        .HasColumnType("int");

                    b.Property<long>("MaschinenId")
                        .HasColumnType("bigint");

                    b.Property<int>("PRnummer")
                        .HasColumnType("int");

                    b.Property<int>("Solltemp1")
                        .HasColumnType("int");

                    b.Property<int>("Solltemp2")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MaschinenId");

                    b.ToTable("Temperaturdaten");
                });

            modelBuilder.Entity("MaschinenDataein.Models.Data.ZustandsDaten", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("MaschinenId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<long>("ZustandsmeldungId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MaschinenId");

                    b.HasIndex("ZustandsmeldungId");

                    b.ToTable("Zustandsdaten");
                });

            modelBuilder.Entity("MaschinenDataein.Models.Data.ZustandsMeldung", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Meldung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Zustandsmeldung");
                });

            modelBuilder.Entity("MaschinenDataein.Models.Data.AbzugsDaten", b =>
                {
                    b.HasOne("MaschinenDataein.Models.Data.Maschine", "Maschine")
                        .WithMany()
                        .HasForeignKey("MaschinenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Maschine");
                });

            modelBuilder.Entity("MaschinenDataein.Models.Data.AlarmDaten", b =>
                {
                    b.HasOne("MaschinenDataein.Models.Data.Maschine", "Maschine")
                        .WithMany()
                        .HasForeignKey("MaschinenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Maschine");
                });

            modelBuilder.Entity("MaschinenDataein.Models.Data.LeistungsDaten", b =>
                {
                    b.HasOne("MaschinenDataein.Models.Data.Maschine", "Maschine")
                        .WithMany()
                        .HasForeignKey("MaschinenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Maschine");
                });

            modelBuilder.Entity("MaschinenDataein.Models.Data.Maschinenprogrammen", b =>
                {
                    b.HasOne("MaschinenDataein.Models.Data.Maschine", "Maschine")
                        .WithMany()
                        .HasForeignKey("MaschinenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Maschine");
                });

            modelBuilder.Entity("MaschinenDataein.Models.Data.StoerungsDaten", b =>
                {
                    b.HasOne("MaschinenDataein.Models.Data.Maschine", "Maschine")
                        .WithMany()
                        .HasForeignKey("MaschinenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MaschinenDataein.Models.Data.StoerungsMeldung", "Stoerungsmeldung")
                        .WithMany()
                        .HasForeignKey("StoerungsmeldungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Maschine");

                    b.Navigation("Stoerungsmeldung");
                });

            modelBuilder.Entity("MaschinenDataein.Models.Data.TemperaturDaten", b =>
                {
                    b.HasOne("MaschinenDataein.Models.Data.Maschine", "Maschine")
                        .WithMany()
                        .HasForeignKey("MaschinenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Maschine");
                });

            modelBuilder.Entity("MaschinenDataein.Models.Data.ZustandsDaten", b =>
                {
                    b.HasOne("MaschinenDataein.Models.Data.Maschine", "Maschine")
                        .WithMany()
                        .HasForeignKey("MaschinenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MaschinenDataein.Models.Data.ZustandsMeldung", "Zustandsmeldung")
                        .WithMany()
                        .HasForeignKey("ZustandsmeldungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Maschine");

                    b.Navigation("Zustandsmeldung");
                });
#pragma warning restore 612, 618
        }
    }
}
